### ISSUE TITLE
Time limit on length of output?

### ISSUE THREAD

**Issue by ediller3** [vye16/slahmr#43]
It seems that the output tracking data is limited to ~6 seconds even when the input videos are longer. Is this just an artifact of the visualization videos? Is there a way to generate longer tracking videos?

**Comment by geopavlakos** [comment]
You can control the length of the video you process from the [config](https://github.com/vye16/slahmr/blob/b5687242765e66bfd1271fc772db10f23ee87cf1/slahmr/confs/data/video.yaml#L17).
With that being said, we recommend running slahmr on shorter sequences, because longer sequences are harder to optimize.
